x-image-tag: &image_tag ${IMAGE_TAG:-develop}  # default 'develop', can set to a SHA

services:
  kafka-consumer:
    image: ghcr.io/rpsbobby/kare8-kafka_consumer:${IMAGE_TAG:-develop}
    pull_policy: always
    ports:
      - "9300:9000"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONPATH=/app:/opt/pythonlibs

  invoice-service:
    image: ghcr.io/rpsbobby/kare8-invoice_service:${IMAGE_TAG:-develop}
    pull_policy: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONPATH=/app:/opt/pythonlibs

  email-service:
    image: ghcr.io/rpsbobby/kare8-email_service:${IMAGE_TAG:-develop}
    pull_policy: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONPATH=/app:/opt/pythonlibs

  order-api:
    image: ghcr.io/rpsbobby/kare8-order_api:${IMAGE_TAG:-develop}
    pull_policy: always
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYTHONPATH=/app:/opt/pythonlibs

  http_spammer:
    image: ghcr.io/rpsbobby/kare8-spammer:${IMAGE_TAG:-develop}
    pull_policy: always
    depends_on:
      - order-api
    environment:
      - API_URL=http://order-api:8000/order
      - GENERATOR_INTERVAL=2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # expose Prometheus UI to host (optional)

volumes:
  grafana-data:
