global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "order-api"
    static_configs:
      - targets: ["order-api:9000"]

  - job_name: "email-service"
    static_configs:
      - targets: ["email-service:9000"]

  - job_name: "invoice-service"
    static_configs:
      - targets: ["invoice-service:9000"]

  - job_name: "kafka-consumer"
    static_configs:
      - targets: ["kafka-consumer:9000"]
