events {}

http {
    upstream order_api {
        server host.docker.internal:30080;  # order-api NodePort
    }

    server {
        listen 80;

        location /order {
            proxy_pass http://order_api;
        }
    }
}
