apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  type: ClusterIP
  selector:
    app: invoice-service
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
spec:
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: ghcr.io/rpsbobby/kare8-invoice_service:develop
          ports:
            - name: metrics
              containerPort: 9000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:29092

