apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: invoice-monitor
spec:
  selector:
    matchLabels:
      app: invoice-service
  endpoints:
    - port: metrics
      interval: 5s
