apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  type: NodePort
  selector:
    app: order-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: metrics
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: ghcr.io/rpsbobby/kare8-order_api:develop
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 9000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:29092

