resources:
  - namespace.yaml
  - order-api
  - kafka-consumer
  - invoice-service
  - email-service
  - prometheus-agent.yaml
  - prometheus-agent-rbac.yaml

namespace: kare8

labels:
  - pairs:
      app.kubernetes.io/part-of: kare8
