apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: email-service-monitor
spec:
  selector:
    matchLabels:
      app: email-service
  endpoints:
    - port: metrics
      interval: 5s
