image:
  repository: ghcr.io/rpsbobby/kare8-kafka_consumer
  tag: develop
service:
  port: null
  metricsPort: 9000
  type: ClusterIP
ingress:
  enabled: false
monitoring:
  enabled: true
  interval: 5s