apiVersion: v1
kind: Service
metadata:
  name: {{ include "kare8-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "kare8-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
