apiVersion: v1
kind: Service
metadata:
  name: {{ include "kare8-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "kare8-service.name" . }}
  ports:
      {{- if .Values.service.port }}
      - name: http
        port: {{ .Values.service.port }}
        targetPort: http
      {{- end }}
      {{- if .Values.service.metricsPort }}
      - name: metrics
        port: {{ .Values.service.metricsPort }}
        targetPort: metrics
      {{- end }}