apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kare8-monitoring.fullname" . }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
    scrape_configs:
    {{- range .Values.scrapeTargets }}
      - job_name: {{ .name }}
        static_configs:
          - targets: ["{{ .host }}:{{ .port }}"]
    {{- end }}
    remote_write:
      - url: {{ .Values.remoteWriteUrl }}
