apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kare8-monitoring.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kare8-monitoring.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kare8-monitoring.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: prometheus-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --enable-feature=agent
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "kare8-monitoring.fullname" . }}-config
