apiVersion: v1
kind: Service
metadata:
  name: {{ include "kare8-monitoring.fullname" . }}
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: {{ include "kare8-monitoring.name" . }}
